# Generated by Django 5.1.4 on 2025-01-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huddle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
    ]
